package edu.vanier.strawberries;

import javafx.geometry.Point2D;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.StackPane;

public abstract class Component extends StackPane {

    /**The first created Node of the element. If the element was generated using a button,
     * this will always be the left node.*/
    protected Node begin;
    /**The second created Node of the element. If the element was generated by a button,
     * this will always be the right node.*/
    protected Node end;
    protected Image DIAGRAM_DISPLAY, IMAGE_DISPLAY;
    public ImageView display;
    public boolean selected;

    public Component(Node begin, Node end) {
        this.begin = begin;
        this.end = end;
        addEventHandler(MouseEvent.MOUSE_PRESSED, this::handleEdit);
        addEventHandler(MouseEvent.MOUSE_DRAGGED, this::handleDrag);
    }

    /**
     * Moving ONE Node (the other one is a pivot)
     * @param movingNode the node being moved
     * @param newX the new X position of the node
     * @param newY the new Y position of the node
     */
    public void moveNode(Node movingNode, double newX, double newY) {
        movingNode.setPosition(newX,newY);
    }

    /**
     * Moving an entire element in the screen, using the Node {@link #begin}
     * @param newX the new X position of the element
     * @param newY the new Y position of the element
     */
    public void moveComponent(double newX, double newY) {
        //get the x and y sizes
        //update node begin to new coordinates
        //update node end to new coordinates + x and y sizes calculated (maintain same angle)
    }

    /** @return the symbol/image of the component */
    public Image getSymbol() {
        return DIAGRAM_DISPLAY;
    }

    public void setBegin(double x, double y) {
        this.begin.setPosition(x,y);
    }

    public void erase() {display=null;}

    public void handleEdit(MouseEvent event) {}

    public void handleDrag(MouseEvent event) {}

    // ABSTRACT methods for each component type

    /**
     * Show/Update the image of the component
     * */
    public abstract void draw();

    public void enableDragAndRotate() {
    }
}

