package com.example.fractal;

import javafx.scene.image.Image;
import javafx.scene.image.ImageView;

public abstract class Component extends ImageView {
    // begin ->  o-----^v^v^v-----o  <- end

    /**The first created Node of the element. If the element was generated using a button,
     * this will always be the left node.*/
    protected Node begin;
    /**The second created Node of the element. If the element was generated by a button,
     * this will always be the right node.*/
    protected Node end;
    protected Image DIAGRAM_DISPLAY, IMAGE_DISPLAY;

    public Component(Node begin, Node end) {
        this.begin = begin;
        this.end = end;
    }

    /**
     * Moving ONE Node (the other one is a pivot)
     * @param movingNode the node being moved
     * @param newX the new X position of the node
     * @param newY the new Y position of the node
     */
    public void moveNode(Node movingNode, double newX, double newY) {
        if (movingNode == begin) {
            begin.setPosition(newX, newY);
        } else if (movingNode == end) {
            end.setPosition(newX, newY);}
    }

    /**
     * Moving an entire element in the screen, using the Node {@link #begin}
     * @param newX the new X position of the element
     * @param newY the new Y position of the element
     */
    public void moveComponent(double newX, double newY) {
        //get the x and y sizes
        //update node begin to new coordinates
        //update node end to new coordinates + x and y sizes calculated (maintain same angle)
    }

    /** @return the symbol/image of the component */
    public Image getSymbol() {
        return DIAGRAM_DISPLAY;
    };

    public void setBegin(double x, double y) {
        
    }

    // ABSTRACT methods for each component type

    /**Show/Update the image of the component*/
    public abstract void draw();
}

