package edu.vanier.strawberries.Models;

import javafx.geometry.Point2D;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.StackPane;

public abstract class Component extends StackPane {

    /**The first created Node of the element. If the element was generated using a button,
     * this will always be the left node.*/
    public Node begin;
    /**The second created Node of the element. If the element was generated by a button,
     * this will always be the right node.*/
    public Node end;
    protected Image DIAGRAM_DISPLAY, IMAGE_DISPLAY;
    public Image display;
    public boolean selected, edit;
    private double angle;

    public Component(Node begin, Node end) {
        this.begin = begin;
        this.end = end;
        angle = 0;
        getChildren().add(new ImageView(display));
    }

    /**
     * Moving ONE Node (the other one is a pivot)
     * @param movingNode the node being moved
     * @param newX the new X position of the node
     * @param newY the new Y position of the node
     */
    public void moveNode(Node movingNode, double newX, double newY) {
        movingNode.setPosition(newX,newY);
    }

    public void setBegin(double x, double y) {
        this.begin.setPosition(x,y);
    }

    public void erase() {display=null;}

    public void markAsSelected(boolean isSelected) {
        selected = isSelected;
    }

    public double getAngle() {
        return angle;
    }

    public boolean isEdit() {
        return edit;
    }

    public void setEdit(boolean state) {
        edit = state;
    }

    /**
     *
     * @param direction "left" or "right", not case-sensitive
     */
    public void rotate(String direction) {
        double newX,newY; // To update END node position after rotation
        switch(direction.toUpperCase()) {
            case "LEFT" -> {
                angle -= 90;
                if(angle==-360) angle = 0;
            }
            case "RIGHT" -> {
                angle += 90;
                if(angle==360) angle = 0;
            }
            default -> {}
        }
        newX = begin.getX() + display.getWidth()*Math.sin(angle);
        newY = begin.getY() - display.getWidth()*Math.cos(angle);
        end.setPosition(newX,newY);
    }

    public double getLength() {
        if(this instanceof Wire) {
            Point2D begin = new Point2D(this.begin.getX(),this.begin.getY());
            return begin.distance(end.getX(),end.getY());
        }
        else if (display!=null) return display.getWidth();
        else return -1; //Something went wrong
    }

    // ABSTRACT methods for each component type

    public void enableDragAndRotate() {
    }
}

