package edu.vanier.strawberries.Models;

import javafx.geometry.Point2D;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.StackPane;

public abstract class Component extends StackPane {

    /**The first created Node of the element. If the element was generated using a button,
     * this will always be the left node.*/
    public Node begin;
    /**The second created Node of the element. If the element was generated by a button,
     * this will always be the right node.*/
    public Node end;
    protected Image DIAGRAM_DISPLAY, IMAGE_DISPLAY;
    public Image display;
    /** The component currently being hovered over */
    public boolean selected;
    /**
     * The most recently selected element when the user pressed down on the mouse
     * @implNote This element will remain the edited component until the user clicks outside of it or clicks on a different component.
     */
    public boolean edit;
    /**  */
    public boolean diagramView;
    private double angle;
    protected double resistance;
    protected double current;
    protected double voltage;
    public boolean isCopy;

    public Component(Node begin, Node end, boolean diagramView) {
        this.begin = begin;
        this.end = end;
        angle = 0;
        this.diagramView = diagramView;
    }

    /**
     * Change the image of the component from a diagram view to a realistic one (and vice-versa).
     * @param diagramView true if the program should display the diagram image.
     */
    public void switchDisplay(boolean diagramView) {
        this.diagramView = diagramView;
        if (diagramView) {
            display = DIAGRAM_DISPLAY;
        } else {
            display = IMAGE_DISPLAY;
        }
    }

    public String getType() {
        return this.getClass().getSimpleName();
    }

    /**
     * Moving ONE Node (the other one is a pivot)
     * @param movingNode the node being moved
     * @param newX the new X position of the node
     * @param newY the new Y position of the node
     */
    public void moveNode(Node movingNode, double newX, double newY) {
        movingNode.setPosition(newX,newY);
    }

    public void markAsSelected(boolean isSelected) {
        selected = isSelected;
    }

    public double getAngle() {
        return angle;
    }

    public double getLength() {
        Point2D src = new Point2D(begin.getX(),begin.getY());
        return src.distance(end.getX(),end.getY());
    }

    public boolean isEdit() {
        return edit;
    }

    public void setEdit(boolean state) {
        edit = state;
    }

    /**
     * @param direction "left" or "right", not case-sensitive
     */
    public void rotate(String direction) {
        double newX,newY; // To update END node position after rotation
        switch(direction.toUpperCase()) {
            case "LEFT" -> {
                angle -= 90;
                if(angle == -90) angle = 270;
                if(angle==-360) angle = 0;
            }
            case "RIGHT" -> {
                angle += 90;
                if(angle==360) angle = 0;
            }
            default -> {}
        }
        updateEnd();
    }

    public void updateEnd() {
        if(!(this instanceof Wire)) {
            double newX = begin.getX() + (display.getWidth() * Math.round(Math.cos(Math.toRadians(angle))));
            double newY = begin.getY() + (display.getWidth() * Math.round(Math.sin(Math.toRadians(angle))));
            end.setPosition(newX, newY);
        }
    }

    public double getResistance() {
        return resistance;
    }

    public void setResistance(double resistance) {
        this.resistance = resistance;
    }

    public double getCurrent() {
        return current;
    }

    public void setCurrent(double current) {
        this.current = current;
    }

    public double getVoltage() {
        return voltage;
    }

    public void setVoltage(double voltage) {
        this.voltage = voltage;
    }

    /**
     * @implNote This method is not meant for instances of the {@link Wire} class
     * @return The coordinates of the upper-left corner of the component's image
     */
    public Point2D getMinimums() {
        boolean vertical = (angle==90 || angle==270);
        double minX,minY,maxX,maxY;
        if(vertical) {
            minX = Math.min(begin.getX(),end.getX()) - (display.getHeight()/2);
            minY = Math.min(begin.getY(),end.getY());
        } else {
            minX = Math.min(begin.getX(),end.getX());
            minY = (begin.getY()-display.getHeight()/2);
        }
        return new Point2D(minX,minY);
    }

    /**
     * @implNote This method is not meant for instances of the {@link Wire} class
     * @return The coordinates of the center of the component's image
     */
    public Point2D getCenter() {
        Point2D minimum = getMinimums();
        double x,y;

        if(angle == 90 || angle == 270) {
            x = minimum.getX() + display.getHeight()/2;
            y = minimum.getY() + display.getWidth()/2;
        }
        else {
            x = minimum.getX() + display.getWidth()/2;
            y = minimum.getY() + display.getHeight()/2;
        }

        return new Point2D(x,y);
    }

    /**
     * Set the center position of the element without having to individually place its Nodes
     * @param x The x position of the center
     * @param y The y position of the center
     */
    public void setCenterPosition(double x, double y) {
        System.out.println("[DEBUG] setting center to: "+x+" , "+y);
        if(this instanceof Wire) {
            double width = Math.abs(begin.getX() - end.getX()),
                   height = Math.abs(begin.getY() - end.getY());
            int multiplierX = (begin.getX() < end.getX()) ? -1 : 1,
                multiplierY = (begin.getY() < end.getY()) ? -1 : 1;
            begin.setPosition(x + (multiplierX*width/2),y+(multiplierY*height/2));
            end.setPosition(x-(multiplierX*width/2),y-(multiplierY*height/2));
        }
        else {
            switch((int) angle) {
                case 0,180 -> {
                    int multiplier = (begin.getX() < end.getX()) ? -1 : 1;
                    begin.setPosition(x + multiplier*(getWidth()), y);
                    end.setPosition(x - multiplier*(getWidth()),y);
                }
                case 90,270 -> {
                    int multiplier = (begin.getY() < end.getY()) ? -1 : 1;
                    begin.setPosition(x,y + multiplier*(getWidth()));
                    end.setPosition(x,y - multiplier*(getWidth()));
                }
            }
        }
    }

    /**
     * Determines if the component was added manually or as a copy of another
     * @param isCopy determines if the element is a copy of another, before it is placed down
     */
    public void setAsCopy(boolean isCopy) {
        this.isCopy = true;
    }

    /**
     * Creates a new Component of the same type and properties as the current (calling) component
     * @return a new instance of Component
     */
    abstract public Component createCopy();
    
}

