package edu.vanier.strawberries.Models;

import javafx.geometry.Point2D;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.StackPane;

public abstract class Component extends StackPane {

    /**The first created Node of the element. If the element was generated using a button,
     * this will always be the left node.*/
    public Node begin;
    /**The second created Node of the element. If the element was generated by a button,
     * this will always be the right node.*/
    public Node end;
    protected Image DIAGRAM_DISPLAY, IMAGE_DISPLAY;
    public Image display;
    public boolean selected, edit;
    private double angle;
    protected double resistance;
    protected double current;
    protected double voltage;

    public Component(Node begin, Node end) {
        this.begin = begin;
        this.end = end;
        angle = 0;
        getChildren().add(new ImageView(display));
    }

    public void switchDisplay(boolean isDiagram) {
        if (isDiagram) {
            display = DIAGRAM_DISPLAY;
        } else {
            display = IMAGE_DISPLAY;
        }
    }

    /**
     * Moving ONE Node (the other one is a pivot)
     * @param movingNode the node being moved
     * @param newX the new X position of the node
     * @param newY the new Y position of the node
     */
    public void moveNode(Node movingNode, double newX, double newY) {
        movingNode.setPosition(newX,newY);
    }

    public void markAsSelected(boolean isSelected) {
        selected = isSelected;
    }

    public double getAngle() {
        return angle;
    }

    public double getLength() {
        Point2D src = new Point2D(begin.getX(),begin.getY());
        return src.distance(end.getX(),end.getY());
    }

    public boolean isEdit() {
        return edit;
    }

    public void setEdit(boolean state) {
        edit = state;
    }

    /**
     *
     * @param direction "left" or "right", not case-sensitive
     */
    public void rotate(String direction) {
        double newX,newY; // To update END node position after rotation
        switch(direction.toUpperCase()) {
            case "LEFT" -> {
                angle -= 90;
                if(angle == -90) angle = 270;
                if(angle==-360) angle = 0;
            }
            case "RIGHT" -> {
                angle += 90;
                if(angle==360) angle = 0;
            }
            default -> {}
        }

        newX = begin.getX() + (display.getWidth() * Math.round(Math.cos(Math.toRadians(angle))));
        newY = begin.getY() + (display.getWidth() * Math.round(Math.sin(Math.toRadians(angle))));
        end.setPosition(newX,newY);
    }

    public double getResistance() {
        return resistance;
    }

    public void setResistance(double resistance) {
        this.resistance = resistance;
    }

    public double getCurrent() {
        return current;
    }

    public void setCurrent(double current) {
        this.current = current;
    }

    public double getVoltage() {
        return voltage;
    }

    public void setVoltage(double voltage) {
        this.voltage = voltage;
    }

    public void calculateCurrent(double voltage) {
        this.voltage = voltage;
        this.current = (resistance != 0) ? voltage / resistance : 0;
    }

    public Point2D getMinimums() {
        boolean vertical = (angle==90 || angle==270);
        double minX,minY,maxX,maxY;
        if(vertical) {
            minX = Math.min(begin.getX(),end.getX()) - (display.getHeight()/2);
            minY = Math.min(begin.getY(),end.getY());
        } else {
            minX = Math.min(begin.getX(),end.getX());
            minY = (begin.getY()-display.getHeight()/2);
        }
        return new Point2D(minX,minY);
    }

    public Point2D getCenter() {
        Point2D minimum = getMinimums();
        double x,y;

        if(angle == 90 || angle == 270) {
            x = minimum.getX() + display.getHeight()/2;
            y = minimum.getY() + display.getWidth()/2;
        }
        else {
            x = minimum.getX() + display.getWidth()/2;
            y = minimum.getY() + display.getHeight()/2;
        }

        return new Point2D(x,y);
    }
}

